# Generated by Django 5.2.6 on 2025-09-24 18:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of the expense", max_length=200
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in INR",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Transport", "Transport"),
                            ("Entertainment", "Entertainment"),
                            ("Utilities", "Utilities"),
                            ("Healthcare", "Healthcare"),
                            ("Shopping", "Shopping"),
                            ("Education", "Education"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        help_text="Category of the expense",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField(help_text="Date when the expense occurred")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the expense",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this expense",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
